const CartActionTypes = {
  ADD_CART_ITEM: "ADD_CART_ITEM",
  CLEAR_CART: "CLEAR_CART",
  CLEAR_ITEM_FROM_CART: "CLEAR_ITEM_FROM_CART",
  PULL_CART_FROM_FIREBASE: 'PULL_CART_FROM_FIREBASE',
  REMOVE_ITEM: "REMOVE_ITEM",
  TOGGLE_CART_HIDDEN: "TOGGLE_CART_HIDDEN",
  UPDATE_CART_IN_FIREBASE: 'UPDATE_CART_IN_FIREBASE'
};

export default CartActionTypes;
